name: skeleton_app
description: Flutter Skeleton – Supabase + BLoC alapú sablon projekt
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.12.0

  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5

  # UI
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.1.0

  # Config / env
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
