#!/bin/zsh
# ============================================================
# Skeleton – Online Supabase dev környezet
#
# Elindítja a Flutter appokat a ROOT/.env-ben lévő
# REMOTE Supabase konfigurációval – Docker nélkül.
#
# Használat:
#   ./start_online.sh          → client + admin
#   ./start_online.sh client   → csak client
#   ./start_online.sh admin    → csak admin
#   ./start_online.sh stop     → portok felszabadítása
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$SCRIPT_DIR/.."
CLIENT_DIR="$ROOT_DIR/Flutter/client"
ADMIN_DIR="$ROOT_DIR/Flutter/admin"
FLUTTER="${FLUTTER_BIN:-/Users/szabi/develop/flutter/bin/flutter}"
ENV_FILE="$ROOT_DIR/.env"

CLIENT_WEB_PORT=3000
ADMIN_WEB_PORT=3001

GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; BOLD='\033[1m'; CYAN='\033[0;36m'; NC='\033[0m'

print_banner() {
  echo ""
  echo "${BOLD}${BLUE}╔══════════════════════════════════════════╗${NC}"
  echo "${BOLD}${BLUE}║   🌐  Skeleton Online Dev Környezet     ║${NC}"
  echo "${BOLD}${BLUE}╚══════════════════════════════════════════╝${NC}"
  echo ""
}

# ── .env + remote URL ellenőrzés ─────────────────────────────
check_env() {
  if [ ! -f "$ENV_FILE" ]; then
    echo "${RED}❌ Hiányzó fájl: $ENV_FILE${NC}"
    exit 1
  fi

  local url
  url=$(grep '^SUPABASE_URL=' "$ENV_FILE" | cut -d'=' -f2-)
  if [[ -z "$url" || "$url" == *"localhost"* || "$url" == *"127.0.0.1"* ]]; then
    echo "${RED}❌ SUPABASE_URL lokális értékre mutat: ${url}${NC}"
    echo "   A root .env-ben az ONLINE Supabase URL-t add meg."
    exit 1
  fi
  echo "${GREEN}✅ Supabase URL: $url${NC}"
}

# ── Flutter .env szinkron (remote értékekkel) ─────────────────
sync_env() {
  local app_dir="$1"
  local url
  local key
  url=$(grep '^SUPABASE_URL=' "$ENV_FILE" | cut -d'=' -f2-)
  key=$(grep '^SUPABASE_ANON_KEY=' "$ENV_FILE" | cut -d'=' -f2-)
  cat > "$app_dir/.env" <<EOF
# Auto-generated by start_online.sh – ne szerkeszd kézzel!
SUPABASE_URL=$url
SUPABASE_ANON_KEY=$key
EOF
  echo "${GREEN}   $(basename $app_dir)/.env → online Supabase${NC}"
}

free_port() {
  local port="$1"
  local pid
  pid=$(lsof -ti tcp:"$port" 2>/dev/null || true)
  if [ -n "$pid" ]; then
    echo "${YELLOW}   Port $port foglalt (PID: $pid) – leállítom...${NC}"
    kill -9 $pid 2>/dev/null || true
    sleep 1
  fi
}

pub_get() {
  local app_dir="$1"
  if [ ! -f "$app_dir/.dart_tool/package_config.json" ]; then
    echo "${YELLOW}   flutter pub get – $(basename $app_dir)...${NC}"
    cd "$app_dir" && "$FLUTTER" pub get --quiet
  fi
}

launch() {
  local app_dir="$1"
  local label="$2"
  local port="$3"
  free_port "$port"
  osascript -e "tell application \"Terminal\" to do script \"cd '$app_dir' && '$FLUTTER' run -d chrome --web-port=$port --web-hostname=localhost\""
  echo "${GREEN}   $label → http://localhost:$port${NC}"
}

stop_all() {
  echo "${YELLOW}⏹️  Portok felszabadítása...${NC}"
  free_port "$CLIENT_WEB_PORT"
  free_port "$ADMIN_WEB_PORT"
  echo "${GREEN}✅ Kész${NC}"
  exit 0
}

# ── Fő logika ─────────────────────────────────────────────────
MODE="${1:-all}"
print_banner
check_env

case "$MODE" in
  stop)
    stop_all
    ;;

  client)
    echo "${CYAN}🎯 Client app indítása (online Supabase)${NC}"
    sync_env "$CLIENT_DIR"
    pub_get "$CLIENT_DIR"
    launch "$CLIENT_DIR" "Skeleton Client" "$CLIENT_WEB_PORT"
    ;;

  admin)
    echo "${CYAN}🎯 Admin app indítása (online Supabase)${NC}"
    sync_env "$ADMIN_DIR"
    pub_get "$ADMIN_DIR"
    launch "$ADMIN_DIR" "Skeleton Admin" "$ADMIN_WEB_PORT"
    ;;

  all|"")
    echo "${CYAN}🎯 Flutter appok indítása (online Supabase, Docker nélkül)${NC}"
    sync_env "$CLIENT_DIR"
    sync_env "$ADMIN_DIR"
    pub_get "$CLIENT_DIR"
    pub_get "$ADMIN_DIR"
    launch "$CLIENT_DIR" "Skeleton Client" "$CLIENT_WEB_PORT"
    sleep 1
    launch "$ADMIN_DIR"  "Skeleton Admin"  "$ADMIN_WEB_PORT"
    ;;

  *)
    echo "${RED}Ismeretlen: $MODE${NC}"
    echo "Használat: $0 [all|client|admin|stop]"
    exit 1
    ;;
esac

echo ""
echo "${BOLD}${GREEN}════════════════════════════════════════${NC}"
echo "${BOLD}${GREEN}  Online dev környezet fut!${NC}"
echo "${BOLD}${GREEN}════════════════════════════════════════${NC}"
echo ""
echo "  Client:  ${BOLD}http://localhost:$CLIENT_WEB_PORT${NC}"
echo "  Admin:   ${BOLD}http://localhost:$ADMIN_WEB_PORT${NC}"
echo ""
echo "${YELLOW}💡 Leállításhoz: ./Scripts/start_online.sh stop${NC}"
echo ""
