#!/bin/zsh
# ============================================================
# Skeleton – Lokális fejlesztői környezet indítása
#
# Elindítja:
#   1. Supabase lokális stack (Docker)
#   2. Flutter client  → http://localhost:3000
#   3. Flutter admin   → http://localhost:3001
#   4. Supabase Studio → http://localhost:54333
#   5. Email fogó UI   → http://localhost:54334
#
# Előfeltételek:
#   - Docker Desktop fut
#   - Flutter telepítve van
#   - ROOT_DIR/.env fájl létezik (egyetlen source of truth)
#
# Használat:
#   ./start_local.sh          → mindent elindít
#   ./start_local.sh supabase → csak Supabase
#   ./start_local.sh flutter  → csak Flutter appok (Supabase már fut)
#   ./start_local.sh stop     → mindent leállít
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$SCRIPT_DIR/.."
SUPABASE_DIR="$ROOT_DIR/Supabase"
CLIENT_DIR="$ROOT_DIR/Flutter/client"
ADMIN_DIR="$ROOT_DIR/Flutter/admin"
FLUTTER="${FLUTTER_BIN:-/Users/szabi/develop/flutter/bin/flutter}"
ENV_FILE="$ROOT_DIR/.env"

CLIENT_WEB_PORT=3000
ADMIN_WEB_PORT=3001

# ── Színek ───────────────────────────────────────────────────
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'
RED='\033[0;31m';   BOLD='\033[1m';    CYAN='\033[0;36m'; NC='\033[0m'

print_banner() {
  echo ""
  echo "${BOLD}${BLUE}╔══════════════════════════════════════════╗${NC}"
  echo "${BOLD}${BLUE}║   🚀  Skeleton Lokális Dev Környezet    ║${NC}"
  echo "${BOLD}${BLUE}╚══════════════════════════════════════════╝${NC}"
  echo ""
}

# ── .env ellenőrzés ──────────────────────────────────────────
check_env() {
  if [ ! -f "$ENV_FILE" ]; then
    echo "${RED}❌ Hiányzó fájl: $ENV_FILE${NC}"
    echo "   Hozd létre a root .env fájlt a szükséges változókkal."
    exit 1
  fi
}

# ── Docker ellenőrzés ─────────────────────────────────────────
check_docker() {
  if ! docker info &>/dev/null; then
    echo "${RED}❌ Docker Desktop nem fut! Indítsd el először.${NC}"
    exit 1
  fi
  echo "${GREEN}✅ Docker fut${NC}"
}

# ── Supabase stack ────────────────────────────────────────────
start_supabase() {
  echo ""
  echo "${CYAN}📦 Supabase lokális stack indítása...${NC}"

  docker compose \
    -f "$SUPABASE_DIR/docker-compose.local.yml" \
    --project-directory "$SUPABASE_DIR" \
    --env-file "$ENV_FILE" \
    up -d --wait 2>&1 | grep -E "Starting|Started|healthy|error|Error" || true

  echo "${GREEN}✅ Supabase fut!${NC}"
  echo "   API:    ${BOLD}http://localhost:54331${NC}"
  echo "   Studio: ${BOLD}http://localhost:54333${NC}"
  echo "   Email:  ${BOLD}http://localhost:54334${NC}"
}

stop_supabase() {
  echo "${YELLOW}⏹️  Supabase leállítása...${NC}"
  docker compose \
    -f "$SUPABASE_DIR/docker-compose.local.yml" \
    --project-directory "$SUPABASE_DIR" \
    --env-file "$ENV_FILE" \
    down
  echo "${GREEN}✅ Supabase leállítva${NC}"
}

# ── Flutter .env szinkronizálása a root .env-ből ──────────────
# flutter_dotenv az app könyvtárából olvassa a .env-t,
# ezért generáljuk azt a root .env alapján.
sync_flutter_env() {
  local app_dir="$1"
  local supabase_url
  local supabase_anon_key
  supabase_url=$(grep '^SUPABASE_URL=' "$ENV_FILE" | cut -d'=' -f2-)
  supabase_anon_key=$(grep '^SUPABASE_ANON_KEY=' "$ENV_FILE" | cut -d'=' -f2-)

  cat > "$app_dir/.env" <<EOF
# Auto-generated by start_local.sh – ne szerkeszd kézzel!
# Forrás: $ENV_FILE
SUPABASE_URL=$supabase_url
SUPABASE_ANON_KEY=$supabase_anon_key
EOF
  echo "${GREEN}   $(basename $app_dir)/.env szinkronizálva${NC}"
}

# ── Web support ellenőrzés ────────────────────────────────────
ensure_web_support() {
  local app_dir="$1"
  local name="$2"
  if [ ! -d "$app_dir/web" ]; then
    echo "${YELLOW}   $name: web support hiányzik – hozzáadom...${NC}"
    cd "$app_dir" && "$FLUTTER" create . --platforms=web --quiet
    echo "${GREEN}   $name: web support hozzáadva${NC}"
  fi
}

# ── Port felszabadítás ────────────────────────────────────────
free_port() {
  local port="$1"
  local pid
  pid=$(lsof -ti tcp:"$port" 2>/dev/null || true)
  if [ -n "$pid" ]; then
    echo "${YELLOW}   Port $port foglalt (PID: $pid) – leállítom...${NC}"
    kill -9 $pid 2>/dev/null || true
    sleep 1
  fi
}

# ── Flutter pub get ───────────────────────────────────────────
flutter_pub_get() {
  local app_dir="$1"
  local name="$2"
  if [ ! -f "$app_dir/.dart_tool/package_config.json" ]; then
    echo "${YELLOW}   $name: flutter pub get...${NC}"
    cd "$app_dir" && "$FLUTTER" pub get --quiet
  fi
}

# ── Flutter futtatás új Terminal ablakban ─────────────────────
launch_flutter() {
  local app_dir="$1"
  local tab_title="$2"
  local port="$3"

  osascript -e "tell application \"Terminal\" to do script \"cd '$app_dir' && '$FLUTTER' run -d chrome --web-port=$port --web-hostname=localhost\""
  echo "${GREEN}OK: $tab_title -> http://localhost:$port${NC}"
}

# ── Leállítás ─────────────────────────────────────────────────
stop_all() {
  echo ""
  echo "${YELLOW}⏹️  Környezet leállítása...${NC}"
  stop_supabase
  echo ""
  echo "${GREEN}✅ Minden leállítva.${NC}"
  echo ""
}

# ── Fő logika ─────────────────────────────────────────────────
MODE="${1:-all}"
print_banner
check_env

case "$MODE" in
  stop)
    stop_all
    exit 0
    ;;

  supabase)
    check_docker
    start_supabase
    ;;

  flutter)
    echo "${CYAN}🎯 Csak Flutter appok indítása (Supabase már fut)${NC}"
    ensure_web_support "$CLIENT_DIR" "Client"
    ensure_web_support "$ADMIN_DIR"  "Admin"
    sync_flutter_env "$CLIENT_DIR"
    sync_flutter_env "$ADMIN_DIR"
    flutter_pub_get "$CLIENT_DIR" "Client"
    flutter_pub_get "$ADMIN_DIR" "Admin"
    sleep 1
    free_port "$CLIENT_WEB_PORT"
    launch_flutter "$CLIENT_DIR" "Skeleton Client" "$CLIENT_WEB_PORT"
    sleep 1
    free_port "$ADMIN_WEB_PORT"
    launch_flutter "$ADMIN_DIR"  "Skeleton Admin"  "$ADMIN_WEB_PORT"
    ;;

  all|"")
    check_docker
    start_supabase
    echo ""
    echo "${CYAN}🎯 Flutter appok előkészítése...${NC}"
    ensure_web_support "$CLIENT_DIR" "Client"
    ensure_web_support "$ADMIN_DIR"  "Admin"
    sync_flutter_env "$CLIENT_DIR"
    sync_flutter_env "$ADMIN_DIR"
    flutter_pub_get "$CLIENT_DIR" "Client"
    flutter_pub_get "$ADMIN_DIR" "Admin"
    echo ""
    echo "${CYAN}🌐 Flutter appok indítása...${NC}"
    sleep 2
    free_port "$CLIENT_WEB_PORT"
    launch_flutter "$CLIENT_DIR" "Skeleton Client" "$CLIENT_WEB_PORT"
    sleep 1
    free_port "$ADMIN_WEB_PORT"
    launch_flutter "$ADMIN_DIR"  "Skeleton Admin"  "$ADMIN_WEB_PORT"
    ;;

  *)
    echo "${RED}Ismeretlen parancs: $MODE${NC}"
    echo "Használat: $0 [all|supabase|flutter|stop]"
    exit 1
    ;;
esac

echo ""
echo "${BOLD}${GREEN}════════════════════════════════════════${NC}"
echo "${BOLD}${GREEN}  Lokális fejlesztői környezet fut!${NC}"
echo "${BOLD}${GREEN}════════════════════════════════════════${NC}"
echo ""
echo "  Client:  ${BOLD}http://localhost:$CLIENT_WEB_PORT${NC}"
echo "  Admin:   ${BOLD}http://localhost:$ADMIN_WEB_PORT${NC}"
echo "  Studio:  ${BOLD}http://localhost:54333${NC}"
echo "  Email:   ${BOLD}http://localhost:54334${NC}"
echo ""
echo "${YELLOW}💡 Leállításhoz: ./Scripts/start_local.sh stop${NC}"
echo ""
